// Code generated by protoc-gen-go. DO NOT EDIT.
// source: middleware.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_SUCCEED Status = 0
	Status_FAILED  Status = 1
)

var Status_name = map[int32]string{
	0: "SUCCEED",
	1: "FAILED",
}

var Status_value = map[string]int32{
	"SUCCEED": 0,
	"FAILED":  1,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_10e8b4c446957f50, []int{0}
}

type Gender int32

const (
	Gender_MALE   Gender = 0
	Gender_FEMALE Gender = 1
)

var Gender_name = map[int32]string{
	0: "MALE",
	1: "FEMALE",
}

var Gender_value = map[string]int32{
	"MALE":   0,
	"FEMALE": 1,
}

func (x Gender) String() string {
	return proto.EnumName(Gender_name, int32(x))
}

func (Gender) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_10e8b4c446957f50, []int{1}
}

type RequestRuleType int32

const (
	RequestRuleType_HOT      RequestRuleType = 0
	RequestRuleType_CLASSIFY RequestRuleType = 1
	RequestRuleType_TOPIC    RequestRuleType = 2
	RequestRuleType_INTEREST RequestRuleType = 3
)

var RequestRuleType_name = map[int32]string{
	0: "HOT",
	1: "CLASSIFY",
	2: "TOPIC",
	3: "INTEREST",
}

var RequestRuleType_value = map[string]int32{
	"HOT":      0,
	"CLASSIFY": 1,
	"TOPIC":    2,
	"INTEREST": 3,
}

func (x RequestRuleType) String() string {
	return proto.EnumName(RequestRuleType_name, int32(x))
}

func (RequestRuleType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_10e8b4c446957f50, []int{2}
}

type UserInfo struct {
	Udid                 string   `protobuf:"bytes,1,opt,name=Udid,proto3" json:"Udid,omitempty"`
	Uid                  int64    `protobuf:"varint,2,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Gender               Gender   `protobuf:"varint,3,opt,name=Gender,proto3,enum=proto.Gender" json:"Gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_10e8b4c446957f50, []int{0}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUdid() string {
	if m != nil {
		return m.Udid
	}
	return ""
}

func (m *UserInfo) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *UserInfo) GetGender() Gender {
	if m != nil {
		return m.Gender
	}
	return Gender_MALE
}

type Passthrough struct {
	ExpId                string   `protobuf:"bytes,1,opt,name=ExpId,proto3" json:"ExpId,omitempty"`
	BucketId             string   `protobuf:"bytes,2,opt,name=BucketId,proto3" json:"BucketId,omitempty"`
	BucketName           string   `protobuf:"bytes,3,opt,name=BucketName,proto3" json:"BucketName,omitempty"`
	Uid                  int64    `protobuf:"varint,4,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Udid                 string   `protobuf:"bytes,5,opt,name=Udid,proto3" json:"Udid,omitempty"`
	AlgId                string   `protobuf:"bytes,6,opt,name=AlgId,proto3" json:"AlgId,omitempty"`
	ServeTime            int64    `protobuf:"varint,7,opt,name=ServeTime,proto3" json:"ServeTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Passthrough) Reset()         { *m = Passthrough{} }
func (m *Passthrough) String() string { return proto.CompactTextString(m) }
func (*Passthrough) ProtoMessage()    {}
func (*Passthrough) Descriptor() ([]byte, []int) {
	return fileDescriptor_10e8b4c446957f50, []int{1}
}

func (m *Passthrough) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Passthrough.Unmarshal(m, b)
}
func (m *Passthrough) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Passthrough.Marshal(b, m, deterministic)
}
func (m *Passthrough) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Passthrough.Merge(m, src)
}
func (m *Passthrough) XXX_Size() int {
	return xxx_messageInfo_Passthrough.Size(m)
}
func (m *Passthrough) XXX_DiscardUnknown() {
	xxx_messageInfo_Passthrough.DiscardUnknown(m)
}

var xxx_messageInfo_Passthrough proto.InternalMessageInfo

func (m *Passthrough) GetExpId() string {
	if m != nil {
		return m.ExpId
	}
	return ""
}

func (m *Passthrough) GetBucketId() string {
	if m != nil {
		return m.BucketId
	}
	return ""
}

func (m *Passthrough) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

func (m *Passthrough) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *Passthrough) GetUdid() string {
	if m != nil {
		return m.Udid
	}
	return ""
}

func (m *Passthrough) GetAlgId() string {
	if m != nil {
		return m.AlgId
	}
	return ""
}

func (m *Passthrough) GetServeTime() int64 {
	if m != nil {
		return m.ServeTime
	}
	return 0
}

type Params struct {
	// 规则召回keys
	RuleKeys []string        `protobuf:"bytes,1,rep,name=rule_keys,json=ruleKeys,proto3" json:"rule_keys,omitempty"`
	RuleSort string          `protobuf:"bytes,2,opt,name=rule_sort,json=ruleSort,proto3" json:"rule_sort,omitempty"`
	RuleType RequestRuleType `protobuf:"varint,3,opt,name=rule_type,json=ruleType,proto3,enum=proto.RequestRuleType" json:"rule_type,omitempty"`
	// 漫画相关召回cids
	SimCids              []int32  `protobuf:"varint,9,rep,packed,name=sim_cids,json=simCids,proto3" json:"sim_cids,omitempty"`
	Len                  int32    `protobuf:"varint,4,opt,name=len,proto3" json:"len,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_10e8b4c446957f50, []int{2}
}

func (m *Params) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Params.Unmarshal(m, b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Params.Marshal(b, m, deterministic)
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return xxx_messageInfo_Params.Size(m)
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetRuleKeys() []string {
	if m != nil {
		return m.RuleKeys
	}
	return nil
}

func (m *Params) GetRuleSort() string {
	if m != nil {
		return m.RuleSort
	}
	return ""
}

func (m *Params) GetRuleType() RequestRuleType {
	if m != nil {
		return m.RuleType
	}
	return RequestRuleType_HOT
}

func (m *Params) GetSimCids() []int32 {
	if m != nil {
		return m.SimCids
	}
	return nil
}

func (m *Params) GetLen() int32 {
	if m != nil {
		return m.Len
	}
	return 0
}

type Log struct {
	Recall               string          `protobuf:"bytes,1,opt,name=recall,proto3" json:"recall,omitempty"`
	Algo                 map[int32]int32 `protobuf:"bytes,2,rep,name=algo,proto3" json:"algo,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Cids                 []int32         `protobuf:"varint,3,rep,packed,name=cids,proto3" json:"cids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Log) Reset()         { *m = Log{} }
func (m *Log) String() string { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()    {}
func (*Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_10e8b4c446957f50, []int{3}
}

func (m *Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Log.Unmarshal(m, b)
}
func (m *Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Log.Marshal(b, m, deterministic)
}
func (m *Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Log.Merge(m, src)
}
func (m *Log) XXX_Size() int {
	return xxx_messageInfo_Log.Size(m)
}
func (m *Log) XXX_DiscardUnknown() {
	xxx_messageInfo_Log.DiscardUnknown(m)
}

var xxx_messageInfo_Log proto.InternalMessageInfo

func (m *Log) GetRecall() string {
	if m != nil {
		return m.Recall
	}
	return ""
}

func (m *Log) GetAlgo() map[int32]int32 {
	if m != nil {
		return m.Algo
	}
	return nil
}

func (m *Log) GetCids() []int32 {
	if m != nil {
		return m.Cids
	}
	return nil
}

type ClassifyRequest struct {
	User                 *UserInfo       `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Length               int32           `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	BussinessId          string          `protobuf:"bytes,3,opt,name=bussiness_id,json=bussinessId,proto3" json:"bussiness_id,omitempty"`
	RuleKeys             []string        `protobuf:"bytes,4,rep,name=rule_keys,json=ruleKeys,proto3" json:"rule_keys,omitempty"`
	RuleSort             string          `protobuf:"bytes,5,opt,name=rule_sort,json=ruleSort,proto3" json:"rule_sort,omitempty"`
	RuleType             RequestRuleType `protobuf:"varint,6,opt,name=rule_type,json=ruleType,proto3,enum=proto.RequestRuleType" json:"rule_type,omitempty"`
	PageNum              int32           `protobuf:"varint,7,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ClassifyRequest) Reset()         { *m = ClassifyRequest{} }
func (m *ClassifyRequest) String() string { return proto.CompactTextString(m) }
func (*ClassifyRequest) ProtoMessage()    {}
func (*ClassifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_10e8b4c446957f50, []int{4}
}

func (m *ClassifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClassifyRequest.Unmarshal(m, b)
}
func (m *ClassifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClassifyRequest.Marshal(b, m, deterministic)
}
func (m *ClassifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClassifyRequest.Merge(m, src)
}
func (m *ClassifyRequest) XXX_Size() int {
	return xxx_messageInfo_ClassifyRequest.Size(m)
}
func (m *ClassifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClassifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClassifyRequest proto.InternalMessageInfo

func (m *ClassifyRequest) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *ClassifyRequest) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *ClassifyRequest) GetBussinessId() string {
	if m != nil {
		return m.BussinessId
	}
	return ""
}

func (m *ClassifyRequest) GetRuleKeys() []string {
	if m != nil {
		return m.RuleKeys
	}
	return nil
}

func (m *ClassifyRequest) GetRuleSort() string {
	if m != nil {
		return m.RuleSort
	}
	return ""
}

func (m *ClassifyRequest) GetRuleType() RequestRuleType {
	if m != nil {
		return m.RuleType
	}
	return RequestRuleType_HOT
}

func (m *ClassifyRequest) GetPageNum() int32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

type ClassifyResponse struct {
	ResponseStatus       Status        `protobuf:"varint,1,opt,name=ResponseStatus,proto3,enum=proto.Status" json:"ResponseStatus,omitempty"`
	Massage              string        `protobuf:"bytes,2,opt,name=Massage,proto3" json:"Massage,omitempty"`
	Data                 *ClassifyData `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ClassifyResponse) Reset()         { *m = ClassifyResponse{} }
func (m *ClassifyResponse) String() string { return proto.CompactTextString(m) }
func (*ClassifyResponse) ProtoMessage()    {}
func (*ClassifyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_10e8b4c446957f50, []int{5}
}

func (m *ClassifyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClassifyResponse.Unmarshal(m, b)
}
func (m *ClassifyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClassifyResponse.Marshal(b, m, deterministic)
}
func (m *ClassifyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClassifyResponse.Merge(m, src)
}
func (m *ClassifyResponse) XXX_Size() int {
	return xxx_messageInfo_ClassifyResponse.Size(m)
}
func (m *ClassifyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClassifyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClassifyResponse proto.InternalMessageInfo

func (m *ClassifyResponse) GetResponseStatus() Status {
	if m != nil {
		return m.ResponseStatus
	}
	return Status_SUCCEED
}

func (m *ClassifyResponse) GetMassage() string {
	if m != nil {
		return m.Massage
	}
	return ""
}

func (m *ClassifyResponse) GetData() *ClassifyData {
	if m != nil {
		return m.Data
	}
	return nil
}

type SectionMoreResponse struct {
	ResponseStatus       Status       `protobuf:"varint,1,opt,name=ResponseStatus,proto3,enum=proto.Status" json:"ResponseStatus,omitempty"`
	Massage              string       `protobuf:"bytes,2,opt,name=Massage,proto3" json:"Massage,omitempty"`
	Data                 *SectionData `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SectionMoreResponse) Reset()         { *m = SectionMoreResponse{} }
func (m *SectionMoreResponse) String() string { return proto.CompactTextString(m) }
func (*SectionMoreResponse) ProtoMessage()    {}
func (*SectionMoreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_10e8b4c446957f50, []int{6}
}

func (m *SectionMoreResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SectionMoreResponse.Unmarshal(m, b)
}
func (m *SectionMoreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SectionMoreResponse.Marshal(b, m, deterministic)
}
func (m *SectionMoreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SectionMoreResponse.Merge(m, src)
}
func (m *SectionMoreResponse) XXX_Size() int {
	return xxx_messageInfo_SectionMoreResponse.Size(m)
}
func (m *SectionMoreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SectionMoreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SectionMoreResponse proto.InternalMessageInfo

func (m *SectionMoreResponse) GetResponseStatus() Status {
	if m != nil {
		return m.ResponseStatus
	}
	return Status_SUCCEED
}

func (m *SectionMoreResponse) GetMassage() string {
	if m != nil {
		return m.Massage
	}
	return ""
}

func (m *SectionMoreResponse) GetData() *SectionData {
	if m != nil {
		return m.Data
	}
	return nil
}

type ClassifyData struct {
	CartoonID            []int32        `protobuf:"varint,1,rep,packed,name=CartoonID,proto3" json:"CartoonID,omitempty"`
	PassthroughActive    bool           `protobuf:"varint,2,opt,name=PassthroughActive,proto3" json:"PassthroughActive,omitempty"`
	Passthroughs         []*Passthrough `protobuf:"bytes,3,rep,name=Passthroughs,proto3" json:"Passthroughs,omitempty"`
	Log                  []*Log         `protobuf:"bytes,4,rep,name=log,proto3" json:"log,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ClassifyData) Reset()         { *m = ClassifyData{} }
func (m *ClassifyData) String() string { return proto.CompactTextString(m) }
func (*ClassifyData) ProtoMessage()    {}
func (*ClassifyData) Descriptor() ([]byte, []int) {
	return fileDescriptor_10e8b4c446957f50, []int{7}
}

func (m *ClassifyData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClassifyData.Unmarshal(m, b)
}
func (m *ClassifyData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClassifyData.Marshal(b, m, deterministic)
}
func (m *ClassifyData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClassifyData.Merge(m, src)
}
func (m *ClassifyData) XXX_Size() int {
	return xxx_messageInfo_ClassifyData.Size(m)
}
func (m *ClassifyData) XXX_DiscardUnknown() {
	xxx_messageInfo_ClassifyData.DiscardUnknown(m)
}

var xxx_messageInfo_ClassifyData proto.InternalMessageInfo

func (m *ClassifyData) GetCartoonID() []int32 {
	if m != nil {
		return m.CartoonID
	}
	return nil
}

func (m *ClassifyData) GetPassthroughActive() bool {
	if m != nil {
		return m.PassthroughActive
	}
	return false
}

func (m *ClassifyData) GetPassthroughs() []*Passthrough {
	if m != nil {
		return m.Passthroughs
	}
	return nil
}

func (m *ClassifyData) GetLog() []*Log {
	if m != nil {
		return m.Log
	}
	return nil
}

type SectionData struct {
	CartoonID            []int32  `protobuf:"varint,1,rep,packed,name=CartoonID,proto3" json:"CartoonID,omitempty"`
	Log                  []*Log   `protobuf:"bytes,2,rep,name=log,proto3" json:"log,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SectionData) Reset()         { *m = SectionData{} }
func (m *SectionData) String() string { return proto.CompactTextString(m) }
func (*SectionData) ProtoMessage()    {}
func (*SectionData) Descriptor() ([]byte, []int) {
	return fileDescriptor_10e8b4c446957f50, []int{8}
}

func (m *SectionData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SectionData.Unmarshal(m, b)
}
func (m *SectionData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SectionData.Marshal(b, m, deterministic)
}
func (m *SectionData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SectionData.Merge(m, src)
}
func (m *SectionData) XXX_Size() int {
	return xxx_messageInfo_SectionData.Size(m)
}
func (m *SectionData) XXX_DiscardUnknown() {
	xxx_messageInfo_SectionData.DiscardUnknown(m)
}

var xxx_messageInfo_SectionData proto.InternalMessageInfo

func (m *SectionData) GetCartoonID() []int32 {
	if m != nil {
		return m.CartoonID
	}
	return nil
}

func (m *SectionData) GetLog() []*Log {
	if m != nil {
		return m.Log
	}
	return nil
}

type MultiCids struct {
	Cids                 []int32  `protobuf:"varint,1,rep,packed,name=cids,proto3" json:"cids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiCids) Reset()         { *m = MultiCids{} }
func (m *MultiCids) String() string { return proto.CompactTextString(m) }
func (*MultiCids) ProtoMessage()    {}
func (*MultiCids) Descriptor() ([]byte, []int) {
	return fileDescriptor_10e8b4c446957f50, []int{9}
}

func (m *MultiCids) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiCids.Unmarshal(m, b)
}
func (m *MultiCids) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiCids.Marshal(b, m, deterministic)
}
func (m *MultiCids) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiCids.Merge(m, src)
}
func (m *MultiCids) XXX_Size() int {
	return xxx_messageInfo_MultiCids.Size(m)
}
func (m *MultiCids) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiCids.DiscardUnknown(m)
}

var xxx_messageInfo_MultiCids proto.InternalMessageInfo

func (m *MultiCids) GetCids() []int32 {
	if m != nil {
		return m.Cids
	}
	return nil
}

type MultiplyRecommendRequest struct {
	User *UserInfo `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	// 规则召回keys
	Params               []*Params `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty"`
	BussinessId          string    `protobuf:"bytes,3,opt,name=bussiness_id,json=bussinessId,proto3" json:"bussiness_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MultiplyRecommendRequest) Reset()         { *m = MultiplyRecommendRequest{} }
func (m *MultiplyRecommendRequest) String() string { return proto.CompactTextString(m) }
func (*MultiplyRecommendRequest) ProtoMessage()    {}
func (*MultiplyRecommendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_10e8b4c446957f50, []int{10}
}

func (m *MultiplyRecommendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiplyRecommendRequest.Unmarshal(m, b)
}
func (m *MultiplyRecommendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiplyRecommendRequest.Marshal(b, m, deterministic)
}
func (m *MultiplyRecommendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiplyRecommendRequest.Merge(m, src)
}
func (m *MultiplyRecommendRequest) XXX_Size() int {
	return xxx_messageInfo_MultiplyRecommendRequest.Size(m)
}
func (m *MultiplyRecommendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiplyRecommendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MultiplyRecommendRequest proto.InternalMessageInfo

func (m *MultiplyRecommendRequest) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *MultiplyRecommendRequest) GetParams() []*Params {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *MultiplyRecommendRequest) GetBussinessId() string {
	if m != nil {
		return m.BussinessId
	}
	return ""
}

type RelateRecommendRequest struct {
	User                 *UserInfo `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	SimCids              []int32   `protobuf:"varint,2,rep,packed,name=sim_cids,json=simCids,proto3" json:"sim_cids,omitempty"`
	BussinessId          string    `protobuf:"bytes,3,opt,name=bussiness_id,json=bussinessId,proto3" json:"bussiness_id,omitempty"`
	Len                  int32     `protobuf:"varint,4,opt,name=len,proto3" json:"len,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RelateRecommendRequest) Reset()         { *m = RelateRecommendRequest{} }
func (m *RelateRecommendRequest) String() string { return proto.CompactTextString(m) }
func (*RelateRecommendRequest) ProtoMessage()    {}
func (*RelateRecommendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_10e8b4c446957f50, []int{11}
}

func (m *RelateRecommendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RelateRecommendRequest.Unmarshal(m, b)
}
func (m *RelateRecommendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RelateRecommendRequest.Marshal(b, m, deterministic)
}
func (m *RelateRecommendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelateRecommendRequest.Merge(m, src)
}
func (m *RelateRecommendRequest) XXX_Size() int {
	return xxx_messageInfo_RelateRecommendRequest.Size(m)
}
func (m *RelateRecommendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RelateRecommendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RelateRecommendRequest proto.InternalMessageInfo

func (m *RelateRecommendRequest) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *RelateRecommendRequest) GetSimCids() []int32 {
	if m != nil {
		return m.SimCids
	}
	return nil
}

func (m *RelateRecommendRequest) GetBussinessId() string {
	if m != nil {
		return m.BussinessId
	}
	return ""
}

func (m *RelateRecommendRequest) GetLen() int32 {
	if m != nil {
		return m.Len
	}
	return 0
}

type MultiplyData struct {
	CartoonIDs           []*MultiCids   `protobuf:"bytes,1,rep,name=CartoonIDs,proto3" json:"CartoonIDs,omitempty"`
	PassthroughActive    bool           `protobuf:"varint,2,opt,name=PassthroughActive,proto3" json:"PassthroughActive,omitempty"`
	Passthroughs         []*Passthrough `protobuf:"bytes,3,rep,name=Passthroughs,proto3" json:"Passthroughs,omitempty"`
	Log                  []*Log         `protobuf:"bytes,4,rep,name=log,proto3" json:"log,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MultiplyData) Reset()         { *m = MultiplyData{} }
func (m *MultiplyData) String() string { return proto.CompactTextString(m) }
func (*MultiplyData) ProtoMessage()    {}
func (*MultiplyData) Descriptor() ([]byte, []int) {
	return fileDescriptor_10e8b4c446957f50, []int{12}
}

func (m *MultiplyData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiplyData.Unmarshal(m, b)
}
func (m *MultiplyData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiplyData.Marshal(b, m, deterministic)
}
func (m *MultiplyData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiplyData.Merge(m, src)
}
func (m *MultiplyData) XXX_Size() int {
	return xxx_messageInfo_MultiplyData.Size(m)
}
func (m *MultiplyData) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiplyData.DiscardUnknown(m)
}

var xxx_messageInfo_MultiplyData proto.InternalMessageInfo

func (m *MultiplyData) GetCartoonIDs() []*MultiCids {
	if m != nil {
		return m.CartoonIDs
	}
	return nil
}

func (m *MultiplyData) GetPassthroughActive() bool {
	if m != nil {
		return m.PassthroughActive
	}
	return false
}

func (m *MultiplyData) GetPassthroughs() []*Passthrough {
	if m != nil {
		return m.Passthroughs
	}
	return nil
}

func (m *MultiplyData) GetLog() []*Log {
	if m != nil {
		return m.Log
	}
	return nil
}

type MultiplyResponse struct {
	ResponseStatus       Status        `protobuf:"varint,1,opt,name=ResponseStatus,proto3,enum=proto.Status" json:"ResponseStatus,omitempty"`
	Massage              string        `protobuf:"bytes,2,opt,name=Massage,proto3" json:"Massage,omitempty"`
	Data                 *MultiplyData `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *MultiplyResponse) Reset()         { *m = MultiplyResponse{} }
func (m *MultiplyResponse) String() string { return proto.CompactTextString(m) }
func (*MultiplyResponse) ProtoMessage()    {}
func (*MultiplyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_10e8b4c446957f50, []int{13}
}

func (m *MultiplyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiplyResponse.Unmarshal(m, b)
}
func (m *MultiplyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiplyResponse.Marshal(b, m, deterministic)
}
func (m *MultiplyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiplyResponse.Merge(m, src)
}
func (m *MultiplyResponse) XXX_Size() int {
	return xxx_messageInfo_MultiplyResponse.Size(m)
}
func (m *MultiplyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiplyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MultiplyResponse proto.InternalMessageInfo

func (m *MultiplyResponse) GetResponseStatus() Status {
	if m != nil {
		return m.ResponseStatus
	}
	return Status_SUCCEED
}

func (m *MultiplyResponse) GetMassage() string {
	if m != nil {
		return m.Massage
	}
	return ""
}

func (m *MultiplyResponse) GetData() *MultiplyData {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto.Status", Status_name, Status_value)
	proto.RegisterEnum("proto.Gender", Gender_name, Gender_value)
	proto.RegisterEnum("proto.RequestRuleType", RequestRuleType_name, RequestRuleType_value)
	proto.RegisterType((*UserInfo)(nil), "proto.UserInfo")
	proto.RegisterType((*Passthrough)(nil), "proto.Passthrough")
	proto.RegisterType((*Params)(nil), "proto.Params")
	proto.RegisterType((*Log)(nil), "proto.Log")
	proto.RegisterMapType((map[int32]int32)(nil), "proto.Log.AlgoEntry")
	proto.RegisterType((*ClassifyRequest)(nil), "proto.ClassifyRequest")
	proto.RegisterType((*ClassifyResponse)(nil), "proto.ClassifyResponse")
	proto.RegisterType((*SectionMoreResponse)(nil), "proto.SectionMoreResponse")
	proto.RegisterType((*ClassifyData)(nil), "proto.ClassifyData")
	proto.RegisterType((*SectionData)(nil), "proto.SectionData")
	proto.RegisterType((*MultiCids)(nil), "proto.MultiCids")
	proto.RegisterType((*MultiplyRecommendRequest)(nil), "proto.MultiplyRecommendRequest")
	proto.RegisterType((*RelateRecommendRequest)(nil), "proto.RelateRecommendRequest")
	proto.RegisterType((*MultiplyData)(nil), "proto.MultiplyData")
	proto.RegisterType((*MultiplyResponse)(nil), "proto.MultiplyResponse")
}

func init() { proto.RegisterFile("middleware.proto", fileDescriptor_10e8b4c446957f50) }

var fileDescriptor_10e8b4c446957f50 = []byte{
	// 977 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0xce, 0xc4, 0x71, 0x7e, 0x4e, 0xd2, 0xad, 0x99, 0xad, 0xba, 0x26, 0x2c, 0xbb, 0x59, 0xa3,
	0x85, 0xa8, 0x42, 0x15, 0xca, 0x8a, 0x1f, 0x71, 0x17, 0xd2, 0x6c, 0xb1, 0x48, 0xba, 0xd5, 0x24,
	0x15, 0xcb, 0x55, 0xe5, 0x8d, 0x67, 0x5d, 0xab, 0xfe, 0x09, 0x9e, 0x71, 0x21, 0x8f, 0x80, 0x04,
	0x5c, 0xf1, 0x08, 0x3c, 0x00, 0xe2, 0x8e, 0x7b, 0xde, 0x8a, 0x1b, 0x34, 0xe3, 0x71, 0xec, 0xa4,
	0xab, 0x52, 0x40, 0xa0, 0xbd, 0xca, 0xf9, 0x19, 0x7f, 0xe7, 0x3b, 0x67, 0xce, 0x39, 0x13, 0x30,
	0x42, 0xdf, 0x75, 0x03, 0xfa, 0x8d, 0x93, 0xd0, 0xc3, 0x65, 0x12, 0xf3, 0x18, 0xeb, 0xf2, 0xc7,
	0xfa, 0x12, 0x9a, 0x67, 0x8c, 0x26, 0x76, 0xf4, 0x32, 0xc6, 0x18, 0x6a, 0x67, 0xae, 0xef, 0x9a,
	0xa8, 0x87, 0xfa, 0x2d, 0x22, 0x65, 0x6c, 0x80, 0x76, 0xe6, 0xbb, 0x66, 0xb5, 0x87, 0xfa, 0x1a,
	0x11, 0x22, 0x7e, 0x0c, 0xf5, 0x63, 0x1a, 0xb9, 0x34, 0x31, 0xb5, 0x1e, 0xea, 0xdf, 0x19, 0xec,
	0x64, 0x80, 0x87, 0x99, 0x91, 0x28, 0xa7, 0xf5, 0x1b, 0x82, 0xf6, 0xa9, 0xc3, 0x18, 0xbf, 0x48,
	0xe2, 0xd4, 0xbb, 0xc0, 0x7b, 0xa0, 0x8f, 0xbf, 0x5d, 0xda, 0x39, 0x7a, 0xa6, 0xe0, 0x2e, 0x34,
	0x3f, 0x4b, 0x17, 0x97, 0x94, 0xdb, 0x59, 0x8c, 0x16, 0x59, 0xeb, 0xf8, 0x01, 0x40, 0x26, 0x9f,
	0x38, 0x21, 0x95, 0xc1, 0x5a, 0xa4, 0x64, 0xc9, 0xa9, 0xd5, 0x0a, 0x6a, 0x79, 0x02, 0x7a, 0x29,
	0x81, 0x3d, 0xd0, 0x87, 0x81, 0x67, 0xbb, 0x66, 0x3d, 0x8b, 0x2b, 0x15, 0x7c, 0x1f, 0x5a, 0x33,
	0x9a, 0x5c, 0xd1, 0xb9, 0x1f, 0x52, 0xb3, 0x21, 0x11, 0x0a, 0x83, 0xf5, 0x33, 0x82, 0xfa, 0xa9,
	0x93, 0x38, 0x21, 0xc3, 0x6f, 0x41, 0x2b, 0x49, 0x03, 0x7a, 0x7e, 0x49, 0x57, 0xcc, 0x44, 0x3d,
	0x4d, 0x30, 0x14, 0x86, 0x2f, 0xe8, 0xaa, 0x70, 0xb2, 0x38, 0xe1, 0x39, 0x7d, 0x61, 0x98, 0xc5,
	0x09, 0xc7, 0x4f, 0x94, 0x93, 0xaf, 0x96, 0x54, 0x95, 0x6a, 0x5f, 0x95, 0x8a, 0xd0, 0xaf, 0x53,
	0xca, 0x38, 0x49, 0x03, 0x3a, 0x5f, 0x2d, 0x69, 0xf6, 0x91, 0x90, 0xf0, 0x9b, 0xd0, 0x64, 0x7e,
	0x78, 0xbe, 0xf0, 0x5d, 0x66, 0xb6, 0x7a, 0x5a, 0x5f, 0x27, 0x0d, 0xe6, 0x87, 0x23, 0xdf, 0x65,
	0x22, 0xdd, 0x80, 0x46, 0x32, 0x5d, 0x9d, 0x08, 0xd1, 0xfa, 0x09, 0x81, 0x36, 0x89, 0x3d, 0xbc,
	0x0f, 0xf5, 0x84, 0x2e, 0x9c, 0x20, 0x50, 0xb5, 0x55, 0x1a, 0xee, 0x43, 0xcd, 0x09, 0xbc, 0xd8,
	0xac, 0xf6, 0xb4, 0x7e, 0x7b, 0xb0, 0xa7, 0x82, 0x4f, 0x62, 0xef, 0x70, 0x18, 0x78, 0xf1, 0x38,
	0xe2, 0xc9, 0x8a, 0xc8, 0x13, 0xa2, 0x70, 0x32, 0xa4, 0x26, 0x43, 0x4a, 0xb9, 0xfb, 0x31, 0xb4,
	0xd6, 0xc7, 0x44, 0xf0, 0x4b, 0xba, 0x92, 0xf8, 0x3a, 0x11, 0xa2, 0xa8, 0xeb, 0x95, 0x13, 0xa4,
	0x54, 0xe6, 0xad, 0x93, 0x4c, 0xf9, 0xb4, 0xfa, 0x09, 0xb2, 0xfe, 0x40, 0xb0, 0x3b, 0x0a, 0x1c,
	0xc6, 0xfc, 0x97, 0x2b, 0x95, 0x29, 0x7e, 0x07, 0x6a, 0x29, 0xa3, 0x89, 0x04, 0x68, 0x0f, 0x76,
	0x15, 0x95, 0xbc, 0xf3, 0x88, 0x74, 0x8a, 0x3c, 0x02, 0x1a, 0x79, 0xfc, 0x42, 0x61, 0x2a, 0x0d,
	0x3f, 0x82, 0xce, 0x8b, 0x94, 0x31, 0x3f, 0xa2, 0x8c, 0x9d, 0xfb, 0xae, 0x6a, 0x85, 0xf6, 0xda,
	0x66, 0xbb, 0x9b, 0xd7, 0x54, 0xbb, 0xe9, 0x9a, 0xf4, 0x9b, 0xae, 0xa9, 0x7e, 0xfb, 0x6b, 0x5a,
	0x3a, 0x1e, 0x3d, 0x8f, 0xd2, 0x50, 0x76, 0x8f, 0x4e, 0x1a, 0x42, 0x3f, 0x49, 0x43, 0xeb, 0x7b,
	0x04, 0x46, 0x91, 0x3d, 0x5b, 0xc6, 0x11, 0xa3, 0xf8, 0x43, 0xb8, 0x93, 0xcb, 0x33, 0xee, 0xf0,
	0x94, 0xc9, 0x42, 0x14, 0xb3, 0x93, 0x19, 0xc9, 0xd6, 0x21, 0x6c, 0x42, 0x63, 0xea, 0x30, 0xe6,
	0x78, 0x54, 0x75, 0x57, 0xae, 0xe2, 0xf7, 0xa0, 0x76, 0xe4, 0x70, 0x47, 0x96, 0xa2, 0x3d, 0xb8,
	0xab, 0x60, 0xf2, 0xb8, 0xc2, 0x45, 0xe4, 0x01, 0xeb, 0x47, 0x04, 0x77, 0x67, 0x74, 0xc1, 0xfd,
	0x38, 0x9a, 0xc6, 0x09, 0xfd, 0xef, 0x18, 0xbd, 0xbb, 0xc1, 0x08, 0xe7, 0x30, 0x59, 0xe8, 0x12,
	0xa1, 0x5f, 0x10, 0x74, 0xca, 0x3c, 0xc5, 0x28, 0x8e, 0x9c, 0x84, 0xc7, 0x71, 0x64, 0x1f, 0xc9,
	0x09, 0xd3, 0x49, 0x61, 0xc0, 0xef, 0xc3, 0x1b, 0xa5, 0x2d, 0x32, 0x5c, 0x70, 0xff, 0x2a, 0x0b,
	0xdd, 0x24, 0xd7, 0x1d, 0xf8, 0x23, 0xe8, 0x94, 0x8c, 0x59, 0x3f, 0x17, 0x64, 0x4a, 0x2e, 0xb2,
	0x71, 0x0e, 0xdf, 0x07, 0x2d, 0x88, 0x3d, 0xd9, 0x38, 0xed, 0x01, 0x14, 0x83, 0x42, 0x84, 0xd9,
	0xb2, 0xa1, 0x5d, 0xca, 0xe3, 0x2f, 0x08, 0x2b, 0xa8, 0xea, 0xab, 0xa1, 0x1e, 0x42, 0x6b, 0x9a,
	0x06, 0xdc, 0x97, 0x13, 0x9d, 0x4f, 0x1d, 0x2a, 0xa6, 0xce, 0xfa, 0x0e, 0x81, 0x29, 0x4f, 0x2c,
	0x83, 0x15, 0xa1, 0x8b, 0x38, 0x0c, 0x69, 0xe4, 0xfe, 0xad, 0x29, 0x7a, 0x0c, 0xf5, 0xa5, 0xdc,
	0x5d, 0x8a, 0xc3, 0xce, 0x3a, 0x7b, 0x61, 0x24, 0xca, 0x79, 0x8b, 0xa1, 0xb2, 0x7e, 0x40, 0xb0,
	0x4f, 0x68, 0xe0, 0x70, 0xfa, 0xcf, 0x98, 0x94, 0x97, 0x59, 0x75, 0x73, 0x99, 0xdd, 0x62, 0xa4,
	0xaf, 0xef, 0xbb, 0xdf, 0x11, 0x74, 0xf2, 0xda, 0xc8, 0x9b, 0xf8, 0x00, 0x60, 0x5d, 0xf8, 0xac,
	0x8c, 0xed, 0x81, 0xa1, 0xb8, 0xac, 0xcb, 0x4c, 0x4a, 0x67, 0x5e, 0x8b, 0x76, 0x12, 0x1b, 0xa2,
	0xb8, 0xe2, 0xff, 0x77, 0x43, 0x94, 0xcb, 0x97, 0x0d, 0xe4, 0xc1, 0x23, 0xa8, 0x2b, 0xb0, 0x36,
	0x34, 0x66, 0x67, 0xa3, 0xd1, 0x78, 0x7c, 0x64, 0x54, 0x30, 0x40, 0xfd, 0xe9, 0xd0, 0x9e, 0x8c,
	0x8f, 0x0c, 0x74, 0xf0, 0x20, 0x7f, 0xf2, 0x71, 0x13, 0x6a, 0xd3, 0xe1, 0x64, 0xac, 0xfc, 0x63,
	0x29, 0xa3, 0x83, 0x21, 0xec, 0x6e, 0xed, 0x4a, 0xdc, 0x00, 0xed, 0xf3, 0x67, 0x73, 0xa3, 0x82,
	0x3b, 0xd0, 0x1c, 0x4d, 0x86, 0xb3, 0x99, 0xfd, 0xf4, 0x2b, 0x03, 0xe1, 0x16, 0xe8, 0xf3, 0x67,
	0xa7, 0xf6, 0xc8, 0xa8, 0x0a, 0x87, 0x7d, 0x32, 0x1f, 0x93, 0xf1, 0x6c, 0x6e, 0x68, 0x83, 0x5f,
	0x35, 0xd8, 0x99, 0xae, 0xff, 0xa3, 0x90, 0xd3, 0x11, 0xb6, 0x61, 0xef, 0x98, 0xf2, 0x62, 0x95,
	0xaa, 0x0e, 0xc4, 0xfb, 0x5b, 0xcb, 0x4e, 0x45, 0xee, 0xde, 0xbb, 0x66, 0xcf, 0x2a, 0x65, 0x55,
	0xf0, 0x73, 0xe8, 0x6e, 0x40, 0x6d, 0xb4, 0x34, 0x7e, 0xb8, 0x55, 0x9b, 0xed, 0x66, 0x5f, 0x23,
	0x6f, 0x5f, 0x9a, 0x55, 0xc1, 0x44, 0x92, 0xbc, 0xf6, 0xe5, 0xbf, 0xc2, 0x3c, 0x01, 0x7c, 0x4c,
	0xf9, 0x36, 0xcb, 0xb7, 0xd7, 0x8f, 0xd2, 0xab, 0x06, 0xf2, 0x26, 0xbc, 0xe7, 0x70, 0xef, 0x98,
	0xf2, 0x8d, 0x47, 0xe0, 0xd6, 0x34, 0xbb, 0x9b, 0x7b, 0xbc, 0xfc, 0x84, 0x58, 0x95, 0x17, 0x75,
	0xe9, 0x7c, 0xf2, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x59, 0x73, 0xc0, 0xba, 0x5e, 0x0a, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MiddlewareRPCClient is the client API for MiddlewareRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MiddlewareRPCClient interface {
	GetClassifyRecommend(ctx context.Context, in *ClassifyRequest, opts ...grpc.CallOption) (*ClassifyResponse, error)
	GetClassifyRelateRecommend(ctx context.Context, in *MultiplyRecommendRequest, opts ...grpc.CallOption) (*MultiplyResponse, error)
	GetMultiplyRecommend(ctx context.Context, in *MultiplyRecommendRequest, opts ...grpc.CallOption) (*MultiplyResponse, error)
	GetRelateRecommend(ctx context.Context, in *RelateRecommendRequest, opts ...grpc.CallOption) (*MultiplyResponse, error)
	GetSectionMoreRecommend(ctx context.Context, in *MultiplyRecommendRequest, opts ...grpc.CallOption) (*SectionMoreResponse, error)
}

type middlewareRPCClient struct {
	cc *grpc.ClientConn
}

func NewMiddlewareRPCClient(cc *grpc.ClientConn) MiddlewareRPCClient {
	return &middlewareRPCClient{cc}
}

func (c *middlewareRPCClient) GetClassifyRecommend(ctx context.Context, in *ClassifyRequest, opts ...grpc.CallOption) (*ClassifyResponse, error) {
	out := new(ClassifyResponse)
	err := c.cc.Invoke(ctx, "/proto.MiddlewareRPC/GetClassifyRecommend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *middlewareRPCClient) GetClassifyRelateRecommend(ctx context.Context, in *MultiplyRecommendRequest, opts ...grpc.CallOption) (*MultiplyResponse, error) {
	out := new(MultiplyResponse)
	err := c.cc.Invoke(ctx, "/proto.MiddlewareRPC/GetClassifyRelateRecommend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *middlewareRPCClient) GetMultiplyRecommend(ctx context.Context, in *MultiplyRecommendRequest, opts ...grpc.CallOption) (*MultiplyResponse, error) {
	out := new(MultiplyResponse)
	err := c.cc.Invoke(ctx, "/proto.MiddlewareRPC/GetMultiplyRecommend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *middlewareRPCClient) GetRelateRecommend(ctx context.Context, in *RelateRecommendRequest, opts ...grpc.CallOption) (*MultiplyResponse, error) {
	out := new(MultiplyResponse)
	err := c.cc.Invoke(ctx, "/proto.MiddlewareRPC/GetRelateRecommend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *middlewareRPCClient) GetSectionMoreRecommend(ctx context.Context, in *MultiplyRecommendRequest, opts ...grpc.CallOption) (*SectionMoreResponse, error) {
	out := new(SectionMoreResponse)
	err := c.cc.Invoke(ctx, "/proto.MiddlewareRPC/GetSectionMoreRecommend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MiddlewareRPCServer is the server API for MiddlewareRPC service.
type MiddlewareRPCServer interface {
	GetClassifyRecommend(context.Context, *ClassifyRequest) (*ClassifyResponse, error)
	GetClassifyRelateRecommend(context.Context, *MultiplyRecommendRequest) (*MultiplyResponse, error)
	GetMultiplyRecommend(context.Context, *MultiplyRecommendRequest) (*MultiplyResponse, error)
	GetRelateRecommend(context.Context, *RelateRecommendRequest) (*MultiplyResponse, error)
	GetSectionMoreRecommend(context.Context, *MultiplyRecommendRequest) (*SectionMoreResponse, error)
}

func RegisterMiddlewareRPCServer(s *grpc.Server, srv MiddlewareRPCServer) {
	s.RegisterService(&_MiddlewareRPC_serviceDesc, srv)
}

func _MiddlewareRPC_GetClassifyRecommend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClassifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiddlewareRPCServer).GetClassifyRecommend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MiddlewareRPC/GetClassifyRecommend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiddlewareRPCServer).GetClassifyRecommend(ctx, req.(*ClassifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MiddlewareRPC_GetClassifyRelateRecommend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiplyRecommendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiddlewareRPCServer).GetClassifyRelateRecommend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MiddlewareRPC/GetClassifyRelateRecommend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiddlewareRPCServer).GetClassifyRelateRecommend(ctx, req.(*MultiplyRecommendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MiddlewareRPC_GetMultiplyRecommend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiplyRecommendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiddlewareRPCServer).GetMultiplyRecommend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MiddlewareRPC/GetMultiplyRecommend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiddlewareRPCServer).GetMultiplyRecommend(ctx, req.(*MultiplyRecommendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MiddlewareRPC_GetRelateRecommend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelateRecommendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiddlewareRPCServer).GetRelateRecommend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MiddlewareRPC/GetRelateRecommend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiddlewareRPCServer).GetRelateRecommend(ctx, req.(*RelateRecommendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MiddlewareRPC_GetSectionMoreRecommend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiplyRecommendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiddlewareRPCServer).GetSectionMoreRecommend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MiddlewareRPC/GetSectionMoreRecommend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiddlewareRPCServer).GetSectionMoreRecommend(ctx, req.(*MultiplyRecommendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MiddlewareRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MiddlewareRPC",
	HandlerType: (*MiddlewareRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetClassifyRecommend",
			Handler:    _MiddlewareRPC_GetClassifyRecommend_Handler,
		},
		{
			MethodName: "GetClassifyRelateRecommend",
			Handler:    _MiddlewareRPC_GetClassifyRelateRecommend_Handler,
		},
		{
			MethodName: "GetMultiplyRecommend",
			Handler:    _MiddlewareRPC_GetMultiplyRecommend_Handler,
		},
		{
			MethodName: "GetRelateRecommend",
			Handler:    _MiddlewareRPC_GetRelateRecommend_Handler,
		},
		{
			MethodName: "GetSectionMoreRecommend",
			Handler:    _MiddlewareRPC_GetSectionMoreRecommend_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "middleware.proto",
}
